# Generated by Django 6.0.2 on 2026-02-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_newsletter', models.BooleanField(default=True)),
                ('enable_reactions', models.BooleanField(default=True)),
                ('enable_comments', models.BooleanField(default=True)),
                ('enable_quick_preview', models.BooleanField(default=True)),
                ('enable_public_api', models.BooleanField(default=True)),
                ('enable_policy_pages', models.BooleanField(default=True)),
                ('enable_sitemap', models.BooleanField(default=True)),
                ('enable_user_registration', models.BooleanField(default=False)),
                ('enable_auto_tagging', models.BooleanField(default=True)),
                ('auto_tagging_max_tags', models.PositiveSmallIntegerField(default=6)),
                ('auto_tagging_max_total_tags', models.PositiveSmallIntegerField(default=12)),
                ('auto_tagging_max_categories', models.PositiveSmallIntegerField(default=3)),
                ('auto_tagging_min_score', models.FloatField(default=1.2)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('read_only_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Feature Controls',
                'verbose_name_plural': 'Feature Controls',
            },
        ),
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_provider', models.CharField(choices=[('none', 'None'), ('ga4', 'Google Analytics 4'), ('gtm', 'Google Tag Manager'), ('plausible', 'Plausible'), ('custom', 'Custom')], default='none', max_length=20)),
                ('ga4_measurement_id', models.CharField(blank=True, max_length=40)),
                ('gtm_container_id', models.CharField(blank=True, max_length=40)),
                ('plausible_domain', models.CharField(blank=True, max_length=120)),
                ('custom_analytics_snippet', models.TextField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=160)),
                ('smtp_sender_name', models.CharField(blank=True, max_length=120)),
                ('smtp_sender_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Integrations',
                'verbose_name_plural': 'Integrations',
            },
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_meta_title', models.CharField(blank=True, max_length=70)),
                ('default_meta_description', models.CharField(blank=True, max_length=170)),
                ('canonical_base_url', models.URLField(blank=True)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('enable_open_graph', models.BooleanField(default=True)),
                ('enable_twitter_cards', models.BooleanField(default=True)),
                ('default_og_image_url', models.URLField(blank=True)),
                ('twitter_site_handle', models.CharField(blank=True, max_length=40)),
                ('organization_schema_name', models.CharField(blank=True, max_length=120)),
                ('organization_schema_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteAppearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('preset', models.CharField(choices=[('aurora', 'Aurora Blue'), ('citrus', 'Citrus Ember'), ('evergreen', 'Evergreen Mint'), ('royal', 'Royal Magenta')], default='aurora', max_length=40)),
            ],
            options={
                'verbose_name': 'Appearance Studio',
                'verbose_name_plural': 'Appearance Studio',
            },
        ),
        migrations.CreateModel(
            name='SiteIdentitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ultimate Blog', max_length=120)),
                ('site_tagline', models.CharField(blank=True, max_length=180)),
                ('admin_brand_name', models.CharField(default='Admin', max_length=120)),
                ('default_author_display', models.CharField(blank=True, max_length=120)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('footer_notice', models.CharField(blank=True, max_length=220)),
                ('legal_company_name', models.CharField(blank=True, max_length=120)),
                ('homepage_cta_label', models.CharField(default='Explore', max_length=40)),
                ('homepage_cta_url', models.CharField(default='/', max_length=220)),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
    ]
