# Generated by Django 6.0.2 on 2026-02-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featurecontrolsettings_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecontrolsettings',
            name='moderate_comments',
            field=models.BooleanField(default=False),
        ),
    ]
