# Generated by Django 6.0.2 on 2026-02-27 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_featurecontrolsettings_moderate_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecontrolsettings',
            name='comment_spam_threshold',
            field=models.PositiveSmallIntegerField(default=70, help_text='Algorithmic moderation threshold (1-100). Higher is stricter.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
