# Generated by Django 6.0.2 on 2026-02-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_featurecontrolsettings_comment_spam_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='bing_site_verification',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='google_site_verification',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='pinterest_site_verification',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='yandex_site_verification',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
