# Generated by Django 6.0.2 on 2026-02-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seosettings_bing_site_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteidentitysettings',
            name='brand_logo_dark_url',
            field=models.CharField(blank=True, help_text='Optional dark-mode logo URL. Falls back to light logo URL.', max_length=320),
        ),
        migrations.AddField(
            model_name='siteidentitysettings',
            name='brand_logo_url',
            field=models.CharField(blank=True, help_text='Absolute or relative logo URL used for light mode.', max_length=320),
        ),
    ]
