# Generated by Django 6.0.2 on 2026-02-27 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_missing_user_profiles(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    UserProfile = apps.get_model("core", "UserProfile")

    for user in User.objects.all().only("id").iterator():
        UserProfile.objects.get_or_create(user_id=user.pk)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteidentitysettings_brand_logo_dark_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('bio', models.CharField(blank=True, max_length=320)),
                ('avatar_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('website_url', models.URLField(blank=True)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.RunPython(create_missing_user_profiles, noop_reverse),
    ]
