# Generated by Django 6.0.2 on 2026-02-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteidentitysettings',
            name='brand_logo_dark_upload',
            field=models.FileField(blank=True, help_text='Optional uploaded logo file for dark mode.', upload_to='branding/logos/'),
        ),
        migrations.AddField(
            model_name='siteidentitysettings',
            name='brand_logo_upload',
            field=models.FileField(blank=True, help_text='Optional uploaded logo file for light mode.', upload_to='branding/logos/'),
        ),
        migrations.AddField(
            model_name='siteidentitysettings',
            name='favicon_dark_upload',
            field=models.FileField(blank=True, help_text='Optional uploaded favicon file for dark mode.', upload_to='branding/favicons/'),
        ),
        migrations.AddField(
            model_name='siteidentitysettings',
            name='favicon_dark_url',
            field=models.CharField(blank=True, help_text='Optional dark-mode favicon URL. Falls back to light favicon.', max_length=320),
        ),
        migrations.AddField(
            model_name='siteidentitysettings',
            name='favicon_upload',
            field=models.FileField(blank=True, help_text='Optional uploaded favicon file for light mode.', upload_to='branding/favicons/'),
        ),
        migrations.AddField(
            model_name='siteidentitysettings',
            name='favicon_url',
            field=models.CharField(blank=True, help_text='Absolute or relative favicon URL used for light mode.', max_length=320),
        ),
    ]
