# Generated by Django 6.0.2 on 2026-02-27 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_siteidentitysettings_brand_logo_dark_upload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featurecontrolsettings",
            name="category_max_depth",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Maximum allowed depth for category paths (e.g. a/b/c = depth 3).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
