# Generated by Django 6.0.2 on 2026-02-22 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_post_metadata(apps, schema_editor):
    Post = apps.get_model("blog", "Post")
    for post in Post.objects.all().iterator():
        body_markdown = post.body_markdown or ""
        excerpt = post.excerpt or body_markdown
        updates = {
            "word_count": max(len(body_markdown.split()), 1),
            "meta_title": (post.meta_title or post.title or "")[:70],
            "meta_description": (post.meta_description or excerpt or "")[:170],
        }
        Post.objects.filter(pk=post.pk).update(**updates)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(default='site', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('subtitle', models.CharField(blank=True, max_length=260)),
                ('excerpt', models.CharField(blank=True, max_length=320)),
                ('body_markdown', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='allow_reactions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_editors_pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=170),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AddField(
            model_name='post',
            name='word_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(backfill_post_metadata, noop_reverse),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_editors_pick', 'is_featured'], name='blog_post_is_edit_1a6da4_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscriber',
            index=models.Index(fields=['email', 'is_active'], name='blog_newsle_email_1533c6_idx'),
        ),
        migrations.AddField(
            model_name='postrevision',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postrevision',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='blog.post'),
        ),
        migrations.AddIndex(
            model_name='postrevision',
            index=models.Index(fields=['post', 'created_at'], name='blog_postre_post_id_837f81_idx'),
        ),
    ]
