# Generated by Django 6.0.2 on 2026-02-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRefreshSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='global', max_length=40, unique=True)),
                ('auto_refresh_enabled', models.BooleanField(default=False)),
                ('post_refresh_interval_hours', models.PositiveIntegerField(default=168)),
                ('page_refresh_interval_hours', models.PositiveIntegerField(default=168)),
                ('max_items_per_run', models.PositiveIntegerField(default=200)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Refresh Timer',
                'verbose_name_plural': 'Content Refresh Timer',
            },
        ),
    ]
