# Generated by Django 6.0.2 on 2026-02-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contentrefreshsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAppearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='global', max_length=40, unique=True)),
                ('mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('preset', models.CharField(choices=[('aurora', 'Aurora Blue'), ('citrus', 'Citrus Ember'), ('evergreen', 'Evergreen Mint'), ('royal', 'Royal Magenta')], default='aurora', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appearance Studio',
                'verbose_name_plural': 'Appearance Studio',
            },
        ),
    ]
