# Generated by Django 6.0.2 on 2026-02-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_siteappearancesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auto_categories',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='auto_primary_topic',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='auto_tagging_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='auto_tags',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
