# Generated by Django 6.0.2 on 2026-02-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_auto_categories_post_auto_primary_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='schema_markup',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='suggested_internal_links',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
