# Generated by Django 6.0.2 on 2026-02-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_schema_markup_post_suggested_internal_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auto_tags_raw',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Raw auto-generated tags from BM25'),
        ),
        migrations.AddField(
            model_name='post',
            name='flesch_score',
            field=models.SmallIntegerField(default=0, editable=False, help_text='Flesch-Kincaid readability 0-100'),
        ),
        migrations.AddField(
            model_name='post',
            name='heading_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='inbound_link_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='internal_link_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_orphan',
            field=models.BooleanField(default=True, editable=False, help_text='No inbound links'),
        ),
        migrations.AddField(
            model_name='post',
            name='keyword_density',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Primary keyword density %', max_digits=4),
        ),
        migrations.AddField(
            model_name='post',
            name='keyword_index',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Keyword → anchor variants mapping'),
        ),
        migrations.AddField(
            model_name='post',
            name='og_image',
            field=models.URLField(blank=True, help_text='Open Graph image URL'),
        ),
        migrations.AddField(
            model_name='post',
            name='robots',
            field=models.CharField(blank=True, default='index, follow', help_text='Meta robots directive', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='search_intent',
            field=models.CharField(blank=True, choices=[('informational', 'Informational'), ('transactional', 'Transactional'), ('navigational', 'Navigational'), ('commercial', 'Commercial')], editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_audit_results',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='25-point audit results'),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_audit_score',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='0-100 score'),
        ),
        migrations.AddField(
            model_name='post',
            name='tfidf_vector',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='TF-IDF scores per term'),
        ),
        migrations.AddField(
            model_name='post',
            name='thin_content_score',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='0-10 score'),
        ),
    ]
