# Generated by Django 6.0.2 on 2026-02-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_auto_tags_raw_post_flesch_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteAppearanceSettings',
        ),
    ]
