# Generated by Django 6.0.2 on 2026-02-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_siteappearancesettings'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_post_id_008395_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_author__9faedb_idx',
        ),
        migrations.RemoveIndex(
            model_name='newslettersubscriber',
            name='blog_newsle_email_1533c6_idx',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.RemoveConstraint(
            model_name='postbookmark',
            name='unique_post_bookmark',
        ),
        migrations.RemoveConstraint(
            model_name='postlike',
            name='unique_post_like',
        ),
        migrations.RemoveIndex(
            model_name='postrevision',
            name='blog_postre_post_id_837f81_idx',
        ),
        migrations.RemoveIndex(
            model_name='postview',
            name='blog_postvi_session_de2c52_idx',
        ),
        migrations.RemoveIndex(
            model_name='postview',
            name='blog_postvi_viewed__23679d_idx',
        ),
        migrations.RemoveField(
            model_name='postbookmark',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postbookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postrevision',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='postrevision',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postview',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postview',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='PostBookmark',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.DeleteModel(
            name='PostRevision',
        ),
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
