# Generated by Django 6.0.2 on 2026-02-25 17:44

import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_blog_commen_post_id_008395_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, help_text='PostgreSQL FTS vector', null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'status', 'published_at'], name='blog_post_author__a0acd9_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_featured', '-published_at'], name='blog_post_is_feat_7251c7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-updated_at'], name='blog_post_updated_261a59_idx'),
        ),
    ]
