# Generated by Django 6.0.2 on 2026-02-25 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_search_vector_post_blog_post_author__a0acd9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('status', 'published')), fields=['status', '-published_at'], name='blog_post_published_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('is_featured', True), ('status', 'published')), fields=['-published_at'], name='blog_post_featured_idx'),
        ),
    ]
