# Generated by Django 6.0.2 on 2026-03-03 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_post_blog_post_published_idx_and_more"),
        ("media", "0002_use_callable_upload_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover_media",
            field=models.ForeignKey(
                blank=True,
                help_text="Managed media file for the cover image (single source of truth).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_for_posts",
                to="media.mediafile",
            ),
        ),
    ]
