# Generated by Django 6.0.2 on 2026-02-25 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_search_vector_post_blog_post_author__a0acd9_idx_and_more'),
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postbookmark',
            index=models.Index(fields=['user', 'created_at'], name='comments_po_user_id_4dc1ca_idx'),
        ),
        migrations.AddIndex(
            model_name='postbookmark',
            index=models.Index(fields=['post', 'created_at'], name='comments_po_post_id_d694ee_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'created_at'], name='comments_po_post_id_1f6b53_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['user', 'created_at'], name='comments_po_user_id_b24e26_idx'),
        ),
        migrations.AddIndex(
            model_name='postrevision',
            index=models.Index(fields=['editor', 'created_at'], name='comments_po_editor__b8b8f0_idx'),
        ),
        migrations.AddIndex(
            model_name='postrevision',
            index=models.Index(fields=['-created_at'], name='comments_po_created_218eef_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['post', 'viewed_at'], name='comments_po_post_id_d13c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['user', '-viewed_at'], name='comments_po_user_id_283a6d_idx'),
        ),
    ]
