# Generated by Django 6.0.2 on 2026-02-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_postbookmark_comments_po_user_id_4dc1ca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderation_reasons',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_score',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
