# Generated by Django 6.0.2 on 2026-02-23 01:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoEngineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='global', max_length=40, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable_checks', models.BooleanField(default=True)),
                ('enable_live_checks', models.BooleanField(default=True)),
                ('warn_only', models.BooleanField(default=True)),
                ('admin_visibility_only', models.BooleanField(default=True)),
                ('auto_fix_enabled', models.BooleanField(default=True)),
                ('auto_fix_after_hours', models.PositiveIntegerField(default=168)),
                ('rotation_interval_hours', models.PositiveIntegerField(default=24)),
                ('min_links_per_doc', models.PositiveSmallIntegerField(default=3)),
                ('whitehat_cap_max_links', models.PositiveSmallIntegerField(default=8)),
                ('rotation_churn_limit_percent', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('stale_days_threshold', models.PositiveSmallIntegerField(default=30)),
                ('noindex_paginated_filters', models.BooleanField(default=True)),
                ('canonical_query_allowlist', models.CharField(blank=True, max_length=255)),
                ('link_suggestion_min_score', models.FloatField(default=0.45)),
                ('auto_update_published_links', models.BooleanField(default=True)),
                ('apply_interlinks_on_audit', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SEO Engine Settings',
                'verbose_name_plural': 'SEO Engine Settings',
            },
        ),
        migrations.CreateModel(
            name='SeoRouteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=120, unique=True)),
                ('title_template', models.CharField(blank=True, max_length=180)),
                ('description_template', models.CharField(blank=True, max_length=220)),
                ('robots_default', models.CharField(default='index,follow', max_length=60)),
                ('og_type', models.CharField(default='website', max_length=30)),
                ('priority', models.FloatField(default=0.6)),
                ('changefreq', models.CharField(default='weekly', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Route Profile',
                'verbose_name_plural': 'SEO Route Profiles',
                'ordering': ('route_name',),
            },
        ),
        migrations.CreateModel(
            name='SeoAuditSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('url', models.CharField(max_length=360)),
                ('route_type', models.CharField(choices=[('post', 'Post'), ('page', 'Page'), ('policy', 'Policy'), ('listing', 'Listing'), ('static', 'Static'), ('other', 'Other')], default='other', max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('passed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('trigger', models.CharField(choices=[('save', 'Save'), ('manual', 'Manual'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('delete', 'Delete')], default='save', max_length=20)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('audited_at', models.DateTimeField(auto_now_add=True)),
                ('auto_fixed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SEO Audit Snapshot',
                'verbose_name_plural': 'SEO Audit Snapshots',
                'ordering': ('-audited_at',),
            },
        ),
        migrations.CreateModel(
            name='SeoIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_key', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fixed', 'Fixed'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('message', models.CharField(max_length=260)),
                ('suggested_fix', models.CharField(blank=True, max_length=260)),
                ('autofixable', models.BooleanField(default=False)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='seo.seoauditsnapshot')),
            ],
            options={
                'verbose_name': 'SEO Issue',
                'verbose_name_plural': 'SEO Issues',
                'ordering': ('severity', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SeoLinkEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveBigIntegerField()),
                ('target_object_id', models.PositiveBigIntegerField()),
                ('anchor_text', models.CharField(max_length=180)),
                ('source_fragment_hash', models.CharField(max_length=40)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('applied', 'Applied'), ('removed', 'Removed')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_outgoing_edges', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_incoming_edges', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SEO Link Edge',
                'verbose_name_plural': 'SEO Link Edges',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SeoMetadataLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('lock_title', models.BooleanField(default=False)),
                ('lock_description', models.BooleanField(default=False)),
                ('lock_canonical', models.BooleanField(default=False)),
                ('lock_og', models.BooleanField(default=False)),
                ('lock_twitter', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SEO Metadata Lock',
                'verbose_name_plural': 'SEO Metadata Locks',
            },
        ),
        migrations.CreateModel(
            name='SeoRedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=320, unique=True)),
                ('target_url', models.CharField(blank=True, max_length=360)),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 Moved Permanently'), (302, '302 Found'), (410, '410 Gone')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('source_model', models.CharField(blank=True, max_length=120)),
                ('source_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=260)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_redirect_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SEO Redirect Rule',
                'verbose_name_plural': 'SEO Redirect Rules',
                'ordering': ('old_path',),
            },
        ),
        migrations.CreateModel(
            name='SeoSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('suggestion_type', models.CharField(choices=[('metadata', 'Metadata'), ('interlink', 'Interlink'), ('redirect', 'Redirect')], max_length=20)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SEO Suggestion',
                'verbose_name_plural': 'SEO Suggestions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='seoauditsnapshot',
            index=models.Index(fields=['content_type', 'object_id', 'audited_at'], name='seo_seoaudi_content_fd3452_idx'),
        ),
        migrations.AddIndex(
            model_name='seoauditsnapshot',
            index=models.Index(fields=['route_type', 'audited_at'], name='seo_seoaudi_route_t_da59a9_idx'),
        ),
        migrations.AddIndex(
            model_name='seoauditsnapshot',
            index=models.Index(fields=['score'], name='seo_seoaudi_score_92fc23_idx'),
        ),
        migrations.AddIndex(
            model_name='seoissue',
            index=models.Index(fields=['status', 'severity'], name='seo_seoissu_status_593739_idx'),
        ),
        migrations.AddIndex(
            model_name='seoissue',
            index=models.Index(fields=['check_key', 'status'], name='seo_seoissu_check_k_45f1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='seolinkedge',
            index=models.Index(fields=['source_content_type', 'source_object_id', 'status'], name='seo_seolink_source__6b9d51_idx'),
        ),
        migrations.AddIndex(
            model_name='seolinkedge',
            index=models.Index(fields=['target_content_type', 'target_object_id', 'status'], name='seo_seolink_target__31b5cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='seometadatalock',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_seo_metadata_lock_target'),
        ),
        migrations.AddIndex(
            model_name='seoredirectrule',
            index=models.Index(fields=['is_active', 'status_code'], name='seo_seoredi_is_acti_e751d9_idx'),
        ),
        migrations.AddIndex(
            model_name='seosuggestion',
            index=models.Index(fields=['content_type', 'object_id', 'status'], name='seo_seosugg_content_bf7198_idx'),
        ),
        migrations.AddIndex(
            model_name='seosuggestion',
            index=models.Index(fields=['suggestion_type', 'status'], name='seo_seosugg_suggest_72c3b7_idx'),
        ),
    ]
