# Generated by Django 6.0.2 on 2026-02-23 04:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('seo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('needs_correction', 'Needs Correction'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SeoScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('full', 'Full'), ('posts', 'Posts'), ('pages', 'Pages'), ('changed_only', 'Changed Only')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('snapshot_count', models.PositiveIntegerField(default=0)),
                ('canceled_requested', models.BooleanField(default=False)),
                ('settings_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.CharField(blank=True, max_length=280)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_scan_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SEO Scan Job',
                'verbose_name_plural': 'SEO Scan Jobs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SeoScanJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('url', models.CharField(max_length=360)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_text', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seo.seoscanjob')),
            ],
            options={
                'verbose_name': 'SEO Scan Job Item',
                'verbose_name_plural': 'SEO Scan Job Items',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SeoSuggestionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('old_payload_json', models.JSONField(blank=True, default=dict)),
                ('new_payload_json', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_suggestion_revisions', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='seo.seosuggestion')),
            ],
            options={
                'verbose_name': 'SEO Suggestion Revision',
                'verbose_name_plural': 'SEO Suggestion Revisions',
                'ordering': ('-edited_at',),
            },
        ),
        migrations.CreateModel(
            name='TaxonomySynonymGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('scope', models.CharField(choices=[('tags', 'Tags'), ('topics', 'Topics'), ('categories', 'Categories'), ('all', 'All')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taxonomy Synonym Group',
                'verbose_name_plural': 'Taxonomy Synonym Groups',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['scope', 'is_active'], name='seo_taxonom_scope_ce75cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'scope'), name='unique_synonym_group_scope')],
            },
        ),
        migrations.CreateModel(
            name='TaxonomySynonymTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=160)),
                ('normalized_term', models.CharField(editable=False, max_length=160)),
                ('is_canonical', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='seo.taxonomysynonymgroup')),
            ],
            options={
                'verbose_name': 'Taxonomy Synonym Term',
                'verbose_name_plural': 'Taxonomy Synonym Terms',
                'ordering': ('group', '-is_canonical', 'term'),
            },
        ),
        migrations.AddIndex(
            model_name='seoscanjob',
            index=models.Index(fields=['status', 'created_at'], name='seo_seoscan_status_f9b92d_idx'),
        ),
        migrations.AddIndex(
            model_name='seoscanjob',
            index=models.Index(fields=['job_type', 'created_at'], name='seo_seoscan_job_typ_f008e8_idx'),
        ),
        migrations.AddIndex(
            model_name='seoscanjobitem',
            index=models.Index(fields=['job', 'status'], name='seo_seoscan_job_id_f3da01_idx'),
        ),
        migrations.AddIndex(
            model_name='seoscanjobitem',
            index=models.Index(fields=['content_type', 'object_id'], name='seo_seoscan_content_9360f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='seoscanjobitem',
            constraint=models.UniqueConstraint(fields=('job', 'content_type', 'object_id'), name='unique_scan_job_target'),
        ),
        migrations.AddIndex(
            model_name='seosuggestionrevision',
            index=models.Index(fields=['suggestion', 'edited_at'], name='seo_seosugg_suggest_6da471_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomysynonymterm',
            index=models.Index(fields=['group', 'is_active'], name='seo_taxonom_group_i_6912b9_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomysynonymterm',
            index=models.Index(fields=['normalized_term'], name='seo_taxonom_normali_cf720f_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxonomysynonymterm',
            constraint=models.UniqueConstraint(fields=('group', 'normalized_term'), name='unique_synonym_term_per_group'),
        ),
    ]
