# Generated by Django 6.0.2 on 2026-02-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_alter_seosuggestion_status_seoscanjob_seoscanjobitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoenginesettings',
            name='autopilot_min_confidence',
            field=models.FloatField(default=0.82),
        ),
    ]
