# Generated by Django 6.0.2 on 2026-02-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_seoenginesettings_autopilot_min_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoscanjob',
            name='job_type',
            field=models.CharField(choices=[('full', 'Full'), ('posts', 'Posts'), ('pages', 'Pages'), ('changed_only', 'Changed Only'), ('interlinks', 'Internal Linking')], default='full', max_length=20),
        ),
    ]
