# Generated by Django 6.0.2 on 2026-03-03 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("seo", "0004_alter_seoscanjob_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seoissue",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("auto_fixed", "Auto-Fixed"),
                    ("fixed", "Fixed"),
                    ("ignored", "Ignored"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SeoChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("interlink_applied", "Interlink Applied"),
                            ("meta_title_fixed", "Meta Title Fixed"),
                            ("meta_desc_fixed", "Meta Description Fixed"),
                            ("canonical_set", "Canonical Set"),
                            ("canonical_fixed", "Canonical Fixed"),
                            ("metadata_approved", "Metadata Approved"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field_name", models.CharField(max_length=60)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Change Log",
                "verbose_name_plural": "SEO Change Logs",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "created_at"],
                        name="seo_seochan_content_bb2b70_idx",
                    ),
                    models.Index(
                        fields=["change_type", "created_at"],
                        name="seo_seochan_change__64aa79_idx",
                    ),
                ],
            },
        ),
    ]
