# Generated by Django 6.0.2 on 2026-03-03 00:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("file", models.FileField(upload_to="media/%Y/%m/")),
                ("original_filename", models.CharField(max_length=260)),
                ("title", models.CharField(blank=True, max_length=260)),
                ("alt_text", models.CharField(blank=True, max_length=260)),
                ("caption", models.CharField(blank=True, max_length=500)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("folder", models.CharField(blank=True, db_index=True, max_length=260)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media File",
                "verbose_name_plural": "Media Files",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["file_type", "is_active"],
                        name="media_media_file_ty_1ff34a_idx",
                    ),
                    models.Index(
                        fields=["folder", "is_active"],
                        name="media_media_folder_34e7f4_idx",
                    ),
                ],
            },
        ),
    ]
