# Generated by Django 6.0.2 on 2026-03-03 00:43

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial_media_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="file",
            field=models.FileField(upload_to=media.models.media_upload_path),
        ),
    ]
