# Generated by Django 6.0.2 on 2026-03-03 00:56

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_use_callable_upload_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="file",
            field=models.FileField(
                max_length=512, upload_to=media.models.media_upload_path
            ),
        ),
    ]
