# Generated by Django 6.0.2 on 2026-02-22 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('nav_label', models.CharField(blank=True, max_length=90)),
                ('summary', models.CharField(blank=True, max_length=320)),
                ('body_markdown', models.TextField()),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('template_key', models.CharField(choices=[('default', 'Default'), ('landing', 'Landing'), ('documentation', 'Documentation')], default='default', max_length=20)),
                ('show_in_navigation', models.BooleanField(default=False)),
                ('nav_order', models.PositiveSmallIntegerField(default=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=170)),
                ('canonical_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('word_count', models.PositiveIntegerField(default=0, editable=False)),
                ('reading_time', models.PositiveSmallIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nav_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('summary', models.CharField(blank=True, max_length=320)),
                ('body_markdown', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_revisions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='pages.page')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug'], name='pages_page_slug_3e99a9_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status', 'published_at'], name='pages_page_status_de97e2_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['show_in_navigation', 'nav_order'], name='pages_page_show_in_3333d6_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['updated_at'], name='pages_page_updated_1c4d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='pagerevision',
            index=models.Index(fields=['page', 'created_at'], name='pages_pager_page_id_6af1f8_idx'),
        ),
    ]
