# Generated by Django 6.0.2 on 2026-03-02 21:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="flesch_score",
            field=models.SmallIntegerField(
                default=0, editable=False, help_text="Flesch-Kincaid readability 0-100"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="heading_count",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="page",
            name="image_count",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="page",
            name="inbound_link_count",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="page",
            name="internal_link_count",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="page",
            name="is_orphan",
            field=models.BooleanField(
                default=True, editable=False, help_text="No inbound links"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="keyword_density",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                editable=False,
                help_text="Primary keyword density %",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="keyword_index",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                help_text="Keyword → anchor variants mapping",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="schema_markup",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="page",
            name="search_intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("informational", "Informational"),
                    ("transactional", "Transactional"),
                    ("navigational", "Navigational"),
                    ("commercial", "Commercial"),
                ],
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="seo_audit_results",
            field=models.JSONField(
                blank=True,
                default=list,
                editable=False,
                help_text="Audit check results",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="seo_audit_score",
            field=models.PositiveSmallIntegerField(
                default=0, editable=False, help_text="0-100 score"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="suggested_internal_links",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="page",
            name="tfidf_vector",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                help_text="TF-IDF scores per term",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="thin_content_score",
            field=models.PositiveSmallIntegerField(
                default=0, editable=False, help_text="0-10 score"
            ),
        ),
    ]
