# Generated by Django 6.0.2 on 2026-03-03 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_increase_file_max_length'),
        ('pages', '0002_add_seo_signal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cover_media',
            field=models.ForeignKey(blank=True, help_text='Managed media file for the cover image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_pages', to='media.mediafile'),
        ),
    ]
